kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: example-blue
  namespace: bluegreen
  labels:
    app: example-blue
    app.kubernetes.io/component: example-blue
    app.kubernetes.io/instance: example-blue
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - example-blue
        from:
          kind: ImageStreamTag
          namespace: bluegreen
          name: 'example-blue:v1'
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentconfig: example-blue
  template:
    metadata:
      labels:
        deploymentconfig: example-blue
    spec:
      containers:
        - name: example-blue
          image: >-
            openshift/deployment-example:v1
          ports:
            - containerPort: 8080
              protocol: TCP