kind: Service
apiVersion: v1
metadata:
  name: example-green
  namespace: bluegreen
  labels:
    app: example-green
    app.kubernetes.io/component: example-green
    app.kubernetes.io/instance: example-green
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080